# Generated by Django 4.2.5 on 2023-10-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
